### ISSUE TITLE
error: Illegal identifier: geometry_msgs::msg::accel is already defined

### ISSUE THREAD

**Issue by vincent-hui** [eProsima/Fast-RTPS-Gen#36]
I  am using 1.0.4. When I generated code with the attached idl files, I got an error

```
vincent@vincent-VirtualBox:/mnt/ramdisk$ fastrtpsgen geometry_msgs/msg/*.idl
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)
Loading templates...
Processing the file geometry_msgs/msg/Accel.idl...
Generating Type definition files...
Generating TopicDataTypes files...
Adding project: geometry_msgs/msg/Accel.idl
Processing the file geometry_msgs/msg/AccelStampednh.idl...
geometry_msgs/msg/AccelStampednh.idl:25:35: error: Illegal identifier: geometry_msgs::msg::accel is already defined (Type: geometry_msgs::msg::Accel=com.eprosima.idl.parser.tree.TypeDeclaration@6b26e945)
Exception in thread "main" java.lang.NullPointerException
	at com.eprosima.fastrtps.fastrtpsgen.execute(fastrtpsgen.java:343)
	at com.eprosima.fastrtps.fastrtpsgen.main(fastrtpsgen.java:1207)
```
[geometry_msgs.zip](https://github.com/eProsima/Fast-RTPS-Gen/files/4759605/geometry_msgs.zip)

**Comment by LuisGP** [comment]
Hi @vincent-hui 

The file `Accel.idl` contains a struct named `Accel` in the scope `geometry_msgs::msg` and the file `AccelStampednh.idl` has another struct in the same scope that defines a member named `accel`.
The problem is that the identifier `accel` becomes illegal due to the previous declaration of the struct `Accel` in the same scope.

As you can see in the [IDL 4.2 specification document](https://www.omg.org/spec/IDL/4.2/PDF), in section 7.2.3.1 Collision Rules, this is the expected behavior.

You have two alternatives to work around this issue:

- Escape (section 7.2.3.2) or rename the member if possible to avoid the collision.
- Use the `-cs` (for case-sensitive) option when executing fastrtpsgen.

**Comment by vincent-hui** [comment]
Thank a lot.

Using the -cs option works for me.
